using SemBroncaAI.Garage.Domain.Entities.SiteManagement;

namespace SemBroncaAI.Garage.Application.Features.SiteManagement;

public sealed record ManagedSiteDashboard(int ActiveSites,int InDevelopment,decimal Mrr,decimal RecurringCosts,decimal EstimatedMargin,int PendingItems,int UpcomingRenewals,IReadOnlyList<ManagedSiteListItem> Items);
public sealed record ManagedSiteListItem(Guid Id,string TradeName,string Domain,ManagedSiteStatus Status,string? HostingProvider,decimal MonthlyFee,decimal RecurringCost,DateOnly? NextDue,ManagedSiteFinancialStatus FinancialStatus,bool Active);
public sealed record ManagedSiteMailboxInput(string Address,string? OwnerName,ManagedSiteMailboxType Type,ManagedSiteResourceStatus Status,string? Notes);
public sealed record ManagedSiteCostInput(string Description,string Category,string? Supplier,decimal Value,ManagedSitePeriodicity Periodicity,DateOnly? NextRenewalOn,string? Notes);
public sealed record ManagedSiteSupportInput(DateTime OccurredAt,string Type,string Description,decimal HoursSpent,bool Billable,decimal AdditionalValue,string? Status,string? Notes);
public sealed record ManagedSiteSaveCommand
{
    public string TradeName {get;init;}=""; public string? LegalName {get;init;} public string? Document {get;init;} public string? ContactName {get;init;} public string? Phone {get;init;} public string? WhatsApp {get;init;} public string? Email {get;init;} public string? Notes {get;init;}
    public string ProjectName {get;init;}=""; public string Domain {get;init;}=""; public string? SiteType {get;init;} public string? Scope {get;init;} public DateOnly? ContractedOn {get;init;} public DateOnly? StartedOn {get;init;} public DateOnly? ExpectedDeliveryOn {get;init;} public DateOnly? PublishedOn {get;init;} public ManagedSiteStatus Status {get;init;} public int ContractedRevisions {get;init;} public int UsedRevisions {get;init;} public bool Active {get;init;}=true;
    public string? DomainRegistrar {get;init;} public string? DomainHolder {get;init;} public bool DomainManagedByClient {get;init;} public DateOnly? DomainRenewalOn {get;init;} public decimal DomainCost {get;init;} public string? DomainNotes {get;init;} public string? DnsProvider {get;init;} public string? DnsNotes {get;init;} public string? HostingProvider {get;init;} public string? HostingPlan {get;init;} public string? HostingAdminUrl {get;init;} public decimal HostingCost {get;init;} public ManagedSitePeriodicity HostingPeriodicity {get;init;} public DateOnly? HostingRenewalOn {get;init;} public ManagedSiteResourceStatus HostingStatus {get;init;} public string? DeployPlatform {get;init;} public string? ProductionUrl {get;init;} public string? StagingUrl {get;init;} public string? RepositoryUrl {get;init;} public string? ProductionBranch {get;init;} public string? DeployNotes {get;init;} public string? CredentialReference {get;init;} public ManagedSiteResourceStatus SslStatus {get;init;} public DateOnly? SslExpiresOn {get;init;}
    public string? EmailProvider {get;init;} public string? EmailPlan {get;init;} public int EmailIncludedCount {get;init;} public decimal EmailCost {get;init;} public ManagedSitePeriodicity EmailPeriodicity {get;init;} public DateOnly? EmailRenewalOn {get;init;} public ManagedSiteResourceStatus EmailStatus {get;init;}
    public decimal DevelopmentContractValue {get;init;} public decimal DevelopmentReceivedValue {get;init;} public string? PaymentMethod {get;init;} public string? PaymentTerms {get;init;} public string? DevelopmentPaymentStatus {get;init;} public decimal MonthlyFee {get;init;} public decimal EstimatedRecurringCost {get;init;} public int DueDay {get;init;} public DateOnly? NextChargeOn {get;init;} public ManagedSiteFinancialStatus FinancialStatus {get;init;}
    public bool HasContract {get;init;} public ManagedSiteContractStatus ContractStatus {get;init;} public DateOnly? ContractStartOn {get;init;} public DateOnly? ContractSignedOn {get;init;} public int ContractTermMonths {get;init;} public int CancellationNoticeDays {get;init;} public int IncludedRevisions {get;init;} public decimal MonthlySupportHours {get;init;} public string? ContractNotes {get;init;}
    public IReadOnlyList<ManagedSiteMailboxInput> Mailboxes {get;init;}=[]; public IReadOnlyList<ManagedSiteCostInput> Costs {get;init;}=[]; public IReadOnlyList<ManagedSiteSupportInput> SupportEntries {get;init;}=[];
}
public sealed record ManagedSiteDetails(Guid Id,ManagedSiteSaveCommand Data,decimal DevelopmentBalance,decimal RecurringCost,decimal RecurringMargin,decimal MarginPercent,decimal SupportHoursThisMonth,decimal SupportHoursRemaining,IReadOnlyList<ManagedSiteHistoryItem> History);
public sealed record ManagedSiteHistoryItem(Guid Id,DateTime CreatedAt,string Text,Guid? ActorId);
public sealed record ManagedSiteFilter(string? Search,ManagedSiteStatus? Status,ManagedSiteFinancialStatus? FinancialStatus,string? Hosting,bool? Active);
public interface IManagedSiteAdministration { Task<ManagedSiteDashboard> DashboardAsync(ManagedSiteFilter filter,CancellationToken token); Task<ManagedSiteDetails?> GetAsync(Guid id,CancellationToken token); Task<Guid> CreateAsync(ManagedSiteSaveCommand command,CancellationToken token); Task<bool> UpdateAsync(Guid id,ManagedSiteSaveCommand command,CancellationToken token); Task<bool> SetActiveAsync(Guid id,bool active,CancellationToken token); Task<bool> AddHistoryAsync(Guid id,string text,CancellationToken token); }
