using SemBroncaAI.Garage.Application.Features.SiteManagement;
using SemBroncaAI.Garage.Domain.Entities.SiteManagement;
namespace SemBroncaAI.Garage.Web.Models;
public sealed class ManagedSiteEditModel
{
 public string TradeName {get;set;}="";public string? LegalName{get;set;}public string? Document{get;set;}public string? ContactName{get;set;}public string? Phone{get;set;}public string? WhatsApp{get;set;}public string? Email{get;set;}public string? Notes{get;set;}
 public string ProjectName{get;set;}="";public string Domain{get;set;}="";public string? SiteType{get;set;}public string? Scope{get;set;}public DateOnly? ContractedOn{get;set;}public DateOnly? StartedOn{get;set;}public DateOnly? ExpectedDeliveryOn{get;set;}public DateOnly? PublishedOn{get;set;}public ManagedSiteStatus Status{get;set;}public int ContractedRevisions{get;set;}public int UsedRevisions{get;set;}public bool Active{get;set;}=true;
 public string? DomainRegistrar{get;set;}public string? DomainHolder{get;set;}public bool DomainManagedByClient{get;set;}public DateOnly? DomainRenewalOn{get;set;}public decimal DomainCost{get;set;}public string? DomainNotes{get;set;}public string? DnsProvider{get;set;}public string? DnsNotes{get;set;}public string? HostingProvider{get;set;}public string? HostingPlan{get;set;}public string? HostingAdminUrl{get;set;}public decimal HostingCost{get;set;}public ManagedSitePeriodicity HostingPeriodicity{get;set;}public DateOnly? HostingRenewalOn{get;set;}public ManagedSiteResourceStatus HostingStatus{get;set;}public string? DeployPlatform{get;set;}public string? ProductionUrl{get;set;}public string? StagingUrl{get;set;}public string? RepositoryUrl{get;set;}public string? ProductionBranch{get;set;}public string? DeployNotes{get;set;}public string? CredentialReference{get;set;}public ManagedSiteResourceStatus SslStatus{get;set;}public DateOnly? SslExpiresOn{get;set;}
 public string? EmailProvider{get;set;}public string? EmailPlan{get;set;}public int EmailIncludedCount{get;set;}public decimal EmailCost{get;set;}public ManagedSitePeriodicity EmailPeriodicity{get;set;}public DateOnly? EmailRenewalOn{get;set;}public ManagedSiteResourceStatus EmailStatus{get;set;}public List<ManagedSiteMailboxInput> Mailboxes{get;set;}=[];
 public decimal DevelopmentContractValue{get;set;}public decimal DevelopmentReceivedValue{get;set;}public string? PaymentMethod{get;set;}public string? PaymentTerms{get;set;}public string? DevelopmentPaymentStatus{get;set;}public decimal MonthlyFee{get;set;}public decimal EstimatedRecurringCost{get;set;}public int DueDay{get;set;}public DateOnly? NextChargeOn{get;set;}public ManagedSiteFinancialStatus FinancialStatus{get;set;}public List<ManagedSiteCostInput> Costs{get;set;}=[];
 public bool HasContract{get;set;}public ManagedSiteContractStatus ContractStatus{get;set;}public DateOnly? ContractStartOn{get;set;}public DateOnly? ContractSignedOn{get;set;}public int ContractTermMonths{get;set;}public int CancellationNoticeDays{get;set;}public int IncludedRevisions{get;set;}public decimal MonthlySupportHours{get;set;}public string? ContractNotes{get;set;}public List<ManagedSiteSupportInput> SupportEntries{get;set;}=[];
 public ManagedSiteSaveCommand ToCommand()=>new(){TradeName=TradeName,LegalName=LegalName,Document=Document,ContactName=ContactName,Phone=Phone,WhatsApp=WhatsApp,Email=Email,Notes=Notes,ProjectName=ProjectName,Domain=Domain,SiteType=SiteType,Scope=Scope,ContractedOn=ContractedOn,StartedOn=StartedOn,ExpectedDeliveryOn=ExpectedDeliveryOn,PublishedOn=PublishedOn,Status=Status,ContractedRevisions=ContractedRevisions,UsedRevisions=UsedRevisions,Active=Active,DomainRegistrar=DomainRegistrar,DomainHolder=DomainHolder,DomainManagedByClient=DomainManagedByClient,DomainRenewalOn=DomainRenewalOn,DomainCost=DomainCost,DomainNotes=DomainNotes,DnsProvider=DnsProvider,DnsNotes=DnsNotes,HostingProvider=HostingProvider,HostingPlan=HostingPlan,HostingAdminUrl=HostingAdminUrl,HostingCost=HostingCost,HostingPeriodicity=HostingPeriodicity,HostingRenewalOn=HostingRenewalOn,HostingStatus=HostingStatus,DeployPlatform=DeployPlatform,ProductionUrl=ProductionUrl,StagingUrl=StagingUrl,RepositoryUrl=RepositoryUrl,ProductionBranch=ProductionBranch,DeployNotes=DeployNotes,CredentialReference=CredentialReference,SslStatus=SslStatus,SslExpiresOn=SslExpiresOn,EmailProvider=EmailProvider,EmailPlan=EmailPlan,EmailIncludedCount=EmailIncludedCount,EmailCost=EmailCost,EmailPeriodicity=EmailPeriodicity,EmailRenewalOn=EmailRenewalOn,EmailStatus=EmailStatus,Mailboxes=Mailboxes,DevelopmentContractValue=DevelopmentContractValue,DevelopmentReceivedValue=DevelopmentReceivedValue,PaymentMethod=PaymentMethod,PaymentTerms=PaymentTerms,DevelopmentPaymentStatus=DevelopmentPaymentStatus,MonthlyFee=MonthlyFee,EstimatedRecurringCost=EstimatedRecurringCost,DueDay=DueDay,NextChargeOn=NextChargeOn,FinancialStatus=FinancialStatus,Costs=Costs,HasContract=HasContract,ContractStatus=ContractStatus,ContractStartOn=ContractStartOn,ContractSignedOn=ContractSignedOn,ContractTermMonths=ContractTermMonths,CancellationNoticeDays=CancellationNoticeDays,IncludedRevisions=IncludedRevisions,MonthlySupportHours=MonthlySupportHours,ContractNotes=ContractNotes,SupportEntries=SupportEntries};
 public static ManagedSiteEditModel From(ManagedSiteSaveCommand d)=>new(){TradeName=d.TradeName,LegalName=d.LegalName,Document=d.Document,ContactName=d.ContactName,Phone=d.Phone,WhatsApp=d.WhatsApp,Email=d.Email,Notes=d.Notes,ProjectName=d.ProjectName,Domain=d.Domain,SiteType=d.SiteType,Scope=d.Scope,ContractedOn=d.ContractedOn,StartedOn=d.StartedOn,ExpectedDeliveryOn=d.ExpectedDeliveryOn,PublishedOn=d.PublishedOn,Status=d.Status,ContractedRevisions=d.ContractedRevisions,UsedRevisions=d.UsedRevisions,Active=d.Active,DomainRegistrar=d.DomainRegistrar,DomainHolder=d.DomainHolder,DomainManagedByClient=d.DomainManagedByClient,DomainRenewalOn=d.DomainRenewalOn,DomainCost=d.DomainCost,DomainNotes=d.DomainNotes,DnsProvider=d.DnsProvider,DnsNotes=d.DnsNotes,HostingProvider=d.HostingProvider,HostingPlan=d.HostingPlan,HostingAdminUrl=d.HostingAdminUrl,HostingCost=d.HostingCost,HostingPeriodicity=d.HostingPeriodicity,HostingRenewalOn=d.HostingRenewalOn,HostingStatus=d.HostingStatus,DeployPlatform=d.DeployPlatform,ProductionUrl=d.ProductionUrl,StagingUrl=d.StagingUrl,RepositoryUrl=d.RepositoryUrl,ProductionBranch=d.ProductionBranch,DeployNotes=d.DeployNotes,CredentialReference=d.CredentialReference,SslStatus=d.SslStatus,SslExpiresOn=d.SslExpiresOn,EmailProvider=d.EmailProvider,EmailPlan=d.EmailPlan,EmailIncludedCount=d.EmailIncludedCount,EmailCost=d.EmailCost,EmailPeriodicity=d.EmailPeriodicity,EmailRenewalOn=d.EmailRenewalOn,EmailStatus=d.EmailStatus,Mailboxes=d.Mailboxes.ToList(),DevelopmentContractValue=d.DevelopmentContractValue,DevelopmentReceivedValue=d.DevelopmentReceivedValue,PaymentMethod=d.PaymentMethod,PaymentTerms=d.PaymentTerms,DevelopmentPaymentStatus=d.DevelopmentPaymentStatus,MonthlyFee=d.MonthlyFee,EstimatedRecurringCost=d.EstimatedRecurringCost,DueDay=d.DueDay,NextChargeOn=d.NextChargeOn,FinancialStatus=d.FinancialStatus,Costs=d.Costs.ToList(),HasContract=d.HasContract,ContractStatus=d.ContractStatus,ContractStartOn=d.ContractStartOn,ContractSignedOn=d.ContractSignedOn,ContractTermMonths=d.ContractTermMonths,CancellationNoticeDays=d.CancellationNoticeDays,IncludedRevisions=d.IncludedRevisions,MonthlySupportHours=d.MonthlySupportHours,ContractNotes=d.ContractNotes,SupportEntries=d.SupportEntries.ToList()};
}
