using System.Security.Cryptography;
using System.Security.Cryptography.X509Certificates;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Npgsql;
using SemBroncaAI.Garage.DataProtection;
using Shouldly;

namespace SemBroncaAI.Garage.Tests.Integration;

[Trait("Category", "PostgreSQLIntegration")]
public sealed class DataProtectionPostgresTests
{
    private static readonly string? ConnectionString =
        Environment.GetEnvironmentVariable("SBGARAGE_INTEGRATION_CONNECTION");

    [PostgresFact]
    public async Task Protected_payload_should_survive_provider_recreation_using_postgresql_key_ring()
    {
        var schema = $"dp_test_{Guid.NewGuid():N}";
        var builder = new NpgsqlConnectionStringBuilder(ConnectionString!) { SearchPath = schema };
        await using var admin = new NpgsqlConnection(ConnectionString);
        await admin.OpenAsync();
        await using (var create = new NpgsqlCommand($"CREATE SCHEMA \"{schema}\"; CREATE TABLE \"{schema}\".\"DataProtectionKeys\" (\"Id\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, \"FriendlyName\" text NULL, \"Xml\" text NULL);", admin))
            await create.ExecuteNonQueryAsync();

        try
        {
            var (certificate, password) = Certificate();
            var configuration = new ConfigurationBuilder().AddInMemoryCollection(new Dictionary<string, string?>
            {
                ["DataProtection:Provider"] = DurableDataProtectionConfiguration.PostgreSqlProvider,
                ["DataProtection:ConnectionString"] = builder.ConnectionString,
                ["DataProtection:CertificateBase64"] = certificate,
                ["DataProtection:CertificatePassword"] = password
            }).Build();

            using var first = Services(configuration);
            var protectedValue = first.GetRequiredService<IDataProtectionProvider>()
                .CreateProtector("restart-test")
                .Protect("session-value");

            using var restarted = Services(configuration);
            restarted.GetRequiredService<IDataProtectionProvider>()
                .CreateProtector("restart-test")
                .Unprotect(protectedValue)
                .ShouldBe("session-value");
        }
        finally
        {
            await using var drop = new NpgsqlCommand($"DROP SCHEMA \"{schema}\" CASCADE;", admin);
            await drop.ExecuteNonQueryAsync();
        }
    }

    private static ServiceProvider Services(IConfiguration configuration)
    {
        var services = new ServiceCollection();
        services.AddLogging();
        DurableDataProtectionConfiguration.Configure(
            services,
            configuration,
            new ProductionEnvironment(),
            "SBGarage.PostgresRestartTest");
        return services.BuildServiceProvider();
    }

    private static (string Certificate, string Password) Certificate()
    {
        const string password = "integration-only-password";
        using var rsa = RSA.Create(2048);
        var request = new CertificateRequest("CN=SBGarage Integration", rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);
        using var certificate = request.CreateSelfSigned(DateTimeOffset.UtcNow.AddMinutes(-1), DateTimeOffset.UtcNow.AddDays(1));
        return (Convert.ToBase64String(certificate.Export(X509ContentType.Pkcs12, password)), password);
    }

    private sealed class ProductionEnvironment : IHostEnvironment
    {
        public string EnvironmentName { get; set; } = Environments.Production;
        public string ApplicationName { get; set; } = "Tests";
        public string ContentRootPath { get; set; } = AppContext.BaseDirectory;
        public Microsoft.Extensions.FileProviders.IFileProvider ContentRootFileProvider { get; set; } =
            new Microsoft.Extensions.FileProviders.NullFileProvider();
    }
}
