using System.Reflection;
using Microsoft.AspNetCore.Authorization;
using SemBroncaAI.Garage.Api.Controllers;
using SemBroncaAI.Garage.Application.Abstractions.Security;
using SemBroncaAI.Garage.Application.Features.SiteManagement;
using Shouldly;

namespace SemBroncaAI.Garage.Tests.Api;
public sealed class PlatformSitesTests
{
 [Fact]public void Site_manager_api_must_remain_inside_platform_admin_boundary(){var authorization=typeof(PlatformSitesController).GetCustomAttribute<AuthorizeAttribute>();authorization.ShouldNotBeNull();authorization.Policy.ShouldBe(PlatformAuthorization.Policy);typeof(PlatformSitesController).GetCustomAttribute<AllowAnonymousAttribute>().ShouldBeNull();}
 [Fact]public void Contracts_must_not_expose_password_or_secret_values(){var names=new[]{typeof(ManagedSiteSaveCommand),typeof(ManagedSiteMailboxInput),typeof(ManagedSiteCostInput)}.SelectMany(x=>x.GetProperties()).Select(x=>x.Name).ToArray();names.ShouldNotContain(x=>x.Contains("Password",StringComparison.OrdinalIgnoreCase));names.ShouldNotContain(x=>x.Contains("Secret",StringComparison.OrdinalIgnoreCase));names.ShouldContain("CredentialReference");}
 [Fact]public void Platform_pages_should_preserve_authorization_responsive_list_and_snackbar_feedback(){var root=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..",".."));var list=File.ReadAllText(Path.Combine(root,"src","SemBroncaAI.Garage.Web","Components","Pages","PlatformSites.razor"));var edit=File.ReadAllText(Path.Combine(root,"src","SemBroncaAI.Garage.Web","Components","Pages","PlatformSiteEdit.razor"));var css=File.ReadAllText(Path.Combine(root,"src","SemBroncaAI.Garage.Web","Components","Pages","PlatformSites.razor.css"));list.ShouldContain("Authorize(Policy=PlatformAuthorization.Policy)");edit.ShouldContain("Authorize(Policy=PlatformAuthorization.Policy)");list.ShouldContain("ISnackbar");edit.ShouldContain("ISnackbar");list.ShouldContain("mobile-list");css.ShouldContain("@media(max-width:720px)");}
 [Fact]public void Site_list_should_keep_filters_and_empty_state_inside_visible_cards(){var root=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..",".."));var page=File.ReadAllText(Path.Combine(root,"src","SemBroncaAI.Garage.Web","Components","Pages","PlatformSites.razor"));page.ShouldContain("filters-card");page.ShouldContain("<thead>");page.ShouldContain("Nenhum site encontrado");page.ShouldContain("Cadastrar primeiro site");page.ShouldContain("Variant=\"Variant.Outlined\"");}
 [Fact]public void Site_form_should_keep_all_tabs_alive_and_preserve_active_panel_state(){var root=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..",".."));var page=File.ReadAllText(Path.Combine(root,"src","SemBroncaAI.Garage.Web","Components","Pages","PlatformSiteEdit.razor"));page.ShouldContain("@bind-ActivePanelIndex=\"_activeTab\"");page.ShouldContain("KeepPanelsAlive=\"true\"");foreach(var tab in new[]{"Cliente","Projeto","Infraestrutura","E-mails","Financeiro","Contrato","Suporte","Histórico"})page.ShouldContain($"Text=\"{tab}\"");}
 [Fact]public void Date_field_should_forward_the_bind_expression_required_during_prerender(){var root=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..",".."));var component=File.ReadAllText(Path.Combine(root,"src","SemBroncaAI.Garage.Web","Components","Shared","DateField.razor"));component.ShouldContain("ValueExpression=\"ValueExpression\"");component.ShouldContain("Expression<Func<DateOnly?>>");}
 [Fact]public void Site_form_styles_should_cross_the_component_boundary_from_a_real_html_wrapper(){var root=Path.GetFullPath(Path.Combine(AppContext.BaseDirectory,"..","..","..","..",".."));var page=File.ReadAllText(Path.Combine(root,"src","SemBroncaAI.Garage.Web","Components","Pages","PlatformSiteEdit.razor"));var css=File.ReadAllText(Path.Combine(root,"src","SemBroncaAI.Garage.Web","Components","Pages","PlatformSiteEdit.razor.css"));page.ShouldContain("<div class=\"site-tabs-shell\">");page.ShouldContain("RequiredError=\"Nome fantasia é obrigatório.\"");css.ShouldContain(".site-tabs-shell ::deep .mud-input");css.ShouldContain(".site-tabs-shell ::deep .date-input");}
}
