<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <RequiresAspNetWebAssets>true</RequiresAspNetWebAssets>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SemBroncaAI.Garage.Application\SemBroncaAI.Garage.Application.csproj" />
  </ItemGroup>

</Project>
